services:
  - type: web
    name: cemetery-mapping-system
    runtime: docker
    repo: https://github.com/bearded7/Cemetry-Mapping-Information-System/tree/master
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cemetery-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

  - type: postgresql
    name: cemetery-db
    plan: free
    ipAllowList: []
    postgresMajorVersion: 15
    databaseName: cemetery_db
    user: postgres